Match Python version prefix
pyenv/pyenv pull request #1656
Opened 2020-07-12 20:03 UTC by varunagrawal

### Description

This PR adds prefix matching when performing `install` operations so users can get away with specifying a prefix string rather than the complete string, making pyenv much more user friendly.

For example, running `pyenv install 3.7` will give the message `python-build: definition not found: 3.7`, but this PR will cause pyenv to install `3.7.8`, the latest version matching `3.7`.

Similary, `pyenv install anaconda3-20` will install `anaconda3-2020.02`.

2020-10-12 21:02 UTC, terencehonles commented
I would think this would also need to be updated in the pyenv global/local commands. I'm interested in doing something like this, but my context is a docker image and with https://github.com/randomknowledge/docker-pyenv-tox/pull/7 I alias the major_minor release at a much deeper level https://github.com/randomknowledge/docker-pyenv-tox/pull/7/files#diff-3254677a7917c6c01f55212f86c57fbfR86-R95

I realized afterwards I could probably create a softlink after building the Python versions instead of before, but for my case it doesn't really make much of a difference and I'm not sure if `pyenv versions --skip-aliases` skipping those is actually better since I want people to not use the point version and use the major_minor version instead (so I don't want the point release visible to the container user)

2020-10-30 01:01 UTC, native-api requested changes
Need to implement the same for other commands accepting a version number. Or I'll be very surprised to get a "version not installed" error for `pyenv install $VER && pyenv global $VER`.

Which raises the question: 

How is this logic supposed to behave when the latest version changes?

2020-12-27 18:27 UTC, varunagrawal commented
If the latest version changes, then `install` should install the new version since the install wouldn't make sense otherwise.

For `global` and `local`, it should use the installed versions. I'll add that functionality.

2020-12-31 05:38 UTC, native-api commented
The most manageable and least surprising implementation will likely be to add an aliases feature like in RVM: https://rvm.io/rubies/alias
`install` then can create a corresponding alias like Travis does: https://travis-ci.org/github/OpenBazaar/official_site/builds/752136085#L203

2020-12-31 05:40 UTC, native-api commented
> The most manageable and least surprising implementation will likely be to add an aliases feature like in RVM

There's already such a plugin: https://github.com/s1341/pyenv-alias

2020-12-31 18:19 UTC, varunagrawal commented on plugins/python-build/bin/python-build
> +    PYTHON_PREFIX_MATCH=$(ls $DEFINITION_DIR -hr | grep ^"${DEFINITION_PATH}" | grep -v "dev" | head -n 1)
Hmm those are good points. I guess I don't have an answer to those questions, so perhaps this PR should be closed.

2021-02-24 13:54 UTC, closed without merging