Update OpenSSL to the supported version
pyenv/pyenv pull request #1712
Opened 2020-10-09 10:38 UTC by davidolrik

Updates OpenSSL to the supported version 1.1.1h as 1.1.0 has several [issues](https://www.openssl.org/news/vulnerabilities-1.1.1.html)

2020-10-09 10:58 UTC, ulgens requested changes

2020-10-09 10:58 UTC, ulgens commented on .vscode/cpx.json
> +{}
Unnecessary & irrelevant change.

2020-10-09 10:58 UTC, ulgens commented on .vscode/settings.json
> +}
Unnecessary & irrelevant change.

2020-10-09 11:32 UTC, davidolrik commented on .vscode/cpx.json
> +{}
Totally agree - my bad

2020-10-11 21:14 UTC, ulgens approved these changes

2021-03-11 05:47 UTC, closed without merging