Add miniconda3 4.8.2, 4.8.3, & 4.9.2
pyenv/pyenv pull request #1763
Opened 2020-12-23 04:05 UTC by pc-fmarin

Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [ ] Here are some details about my PR

Update miniconda 4.8.2, 4.8.3, & 4.9.2 w/ py7, py8, and py9 versions

### Tests
- [ ] My PR adds the following unit tests (if any)

2021-01-09 16:54 UTC, anton-petrov approved these changes
All versions is up to date.

2021-01-10 04:05 UTC, yyuu reviewed
At the first glance, I was surprised with the naming of those new definition files (e.g. use of underscore), however, it seems like it's just following the naming convention of upstream as they are. I think, just using the upstream naming would be good and intuitive for most uses. Any opinions/insights? 🤔

2021-01-10 07:05 UTC, anton-petrov commented
> At the first glance, I was surprised with the naming of those new definition files (e.g. use of underscore), however, it seems like it's just following the naming convention of upstream as they are. I think, just using the upstream naming would be good and intuitive for most uses. Any opinions/insights? 🤔

I fully agree that file naming should be standard, a general approach should be followed, we shouldn't use underscores in filenames, IMHO

2021-01-10 15:02 UTC, anton-petrov requested changes
It might be worth changing the naming of the files a bit...? Like miniconda3-**3.7**-4.8.3, where 3.7 is the python version.

2021-01-10 15:04 UTC, anton-petrov reviewed
It might be worth changing the naming of the files a bit, like miniconda3-**3.7**-4.8.3? Where 3.7 is the python version, 4.8.3 - version of miniconda.

2021-01-29 14:05 UTC, anton-petrov approved these changes

2021-01-29 14:06 UTC, merged