Use command -v instead of which in python-build test
pyenv/pyenv pull request #2144
Opened 2021-11-04 07:11 UTC by scop

Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.  (not applicable)
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [x] Here are some details about my PR

`which` has been deprecated in Debian's debianutils 5.0+ (currently only
Debian unstable), use `command -v` instead like is already done
elsewhere.

### Tests
- [ ] My PR adds the following unit tests (if any)

2021-11-04 13:06 UTC, native-api requested changes
These are not all the useages.

And what would be the replacement for `which -a` (which is also used)?

2021-11-04 20:08 UTC, scop commented
They were all I could find in a quick search, there's a lot of `pyenv which` that are obviously a different thing. But let me know what I missed in addition to the `which -a`.

One possibility for `which -a` would be `whereis -b`, done here now.

2021-11-09 06:57 UTC, native-api commented
> `which` has been deprecated in Debian's debianutils 5.0+ (currently only
> Debian unstable), use `command -v` instead like is already done
> elsewhere.

Could you also link to the source of that and relevant discussion? I'm quite interested in the rationale and officially suggested alternatives.

2021-11-10 07:08 UTC, scop commented
https://salsa.debian.org/debian/debianutils/-/commit/3a8dd10b4502f7bae8fc6973c13ce23fc9da7efb
https://salsa.debian.org/debian/debianutils/-/commit/610a65c6ef040872a124576ddb504c2d4918e880

I'm not aware of a related mailing list or such discussion (but would be surprised if it didn't exist).

2021-11-11 08:37 UTC, native-api commented
> https://salsa.debian.org/debian/debianutils/-/commit/3a8dd10b4502f7bae8fc6973c13ce23fc9da7efb

Okay, they suggest `type` and `command` as replacements and the rationale is:

> Since `type` and `command -v`
> were mandated by POSIX, this utility is no longer useful for
> maintainer scripts and thus will be removed from debianutils.

So they think it's not useful _for maintainer scripts._

---

The replacement for `which -a` is `type -aP`.
`whereis` as a bad replacement since its output has to be parsed and it can only use spaces as delimiters.

---

HOWEVER. I see this utility missing from `debianutils` `4.9.1`... but [present again in `4.11.2`](https://packages.ubuntu.com/impish/amd64/debianutils/filelist)! Looks like it was reintroduced?

2021-11-11 16:10 UTC, scop commented
> So they think it's not useful _for maintainer scripts._

As it stands, there's no other implementation of it in the repos, so the only implementation there actually is is scheduled for removal.

> The replacement for `which -a` is `type -aP`. `whereis` is a bad replacement since its output has to be parsed and it can only use spaces as delimiters.

Agree `whereis` is far from nice due to parsing, but also because it's not standard either. But `type -aP` isn't all that good either, because `-a` and `-P` to it are not portable: neither is in POSIX, zsh type doesn't have -P, FreeBSD sh type has neither.

> HOWEVER. I see this utility missing from `debianutils` `4.9.1`... but [present again in `4.11.2`](https://packages.ubuntu.com/impish/amd64/debianutils/filelist)! Looks like it was reintroduced? Edit: actually, it's present in `4.9.1`, too. They just moved it from `/bin` to `/usr/bin`.

Yes, it's "only" deprecated for now, not yet removed.

2021-11-11 16:13 UTC, native-api commented
> But `type -aP` isn't all that good either, because `-a` and `-P` to it are not portable: neither is in POSIX, zsh type doesn't have -P, FreeBSD sh type has neither.

Pyenv is written in Bash (except eval'ed blocks which are different for different shells) so we only have to care about different Bash versions.

2021-11-11 16:44 UTC, scop commented
But of course :facepalm:, thanks for the sanity check. Switched to `type -aP` now.

2021-11-11 18:08 UTC, merged