Add instructions for nushell on MacOS, Linux and Windows
pyenv/pyenv pull request #2916
Opened 2024-02-29 05:26 UTC by jordanst3wart

### Description
Added instructions on how to setup pyenv with nushell on MacOS, Linux, and Windows.

For the moment this instruction are also found here:
https://www.nushell.sh/book/configuration.html#pyenv

2024-02-29 15:45 UTC, native-api requested changes

2024-02-29 15:45 UTC, native-api commented on README.md
> +    Windows users need to install [pyenv-win](https://github.com/pyenv-win/pyenv-win)
Pyenv-win is a different, independent project.

2024-02-29 15:45 UTC, native-api commented on README.md
> +    ~~~ nu
No adding `$PYENV_ROOT/bin` to PATH?

2024-12-21 09:28 UTC, KamilKleina commented
Hey guys,
any chance autocompletition will be supported for pyenv with nushell?

2025-02-28 19:11 UTC, native-api commented
@KamilKleina you can resolve the above-mentioned issues by making a PR to this PR by specifying thew PR branch as the base branch. It will be in @jordanst3wart 's fork but I'll be able to merge it because I have write access to the PR branch.

2025-05-18 09:20 UTC, merged